# OpenSSL cipher string
#
# This is an OpenSSL specific configuration option for configuring the default
# ciphers. If not set, the value configured at build time ("DEFAULT:!EXP:!LOW"
# by default) is used.
# See https://www.openssl.org/docs/apps/ciphers.html for OpenSSL documentation
# on cipher suite configuration. This is applicable only if wpa_supplicant is
# built to use OpenSSL.
#openssl_ciphers=ECDHE-ECDSA-AES128-CCM

# EAP-EDHOC configuration.
network={
	ssid="ExampleSSID"
	key_mgmt=WPA-EAP
	eap=EDHOC
	identity="user"
	password="foobar"
	priority=2
}

# EAP-PSK configuration.
network={
	ssid="ExampleSSID"
	key_mgmt=WPA-EAP
	eap=PSK
	anonymous_identity="user"
	password=06b4be19da289f475aa46a33cb793029
	identity="eap_psk_user@example.com"
}

# EAP-TLS configuration.
network={
	ssid="ExampleSSID"
	scan_ssid=1
	key_mgmt=WPA-EAP
	pairwise=CCMP TKIP
	group=CCMP TKIP
	eap=TLS
	identity="user"
	ca_cert="../../demoCA_P256/cacert.pem"
	client_cert="../../demoCA_P256/peer-cert.pem"
	private_key="../../demoCA_P256/peer-key.pem"
	private_key_passwd="whatever"
}

